### ISSUE TITLE
Repositories not found 

### ISSUE THREAD

**Issue by aaryan778** [0xApt/awesome-bbht#5]
## Tools Affected:

1.  XSS Finder (XSS) 
2. Open Redirect Scanner 

## SCRIPT OUTPUT

XSS FINDER
--------------------
![XSSFINDER_NOT_FOUND](https://user-images.githubusercontent.com/56699039/148870045-2e9b98ce-2381-454f-8394-cb513752f6b2.png)

Open Redirect Scanner
---------------------------
![OPENREDIRECT_SCANNER_NOT_FOUND](https://user-images.githubusercontent.com/56699039/148870075-7189e9f7-9bbf-4634-9ee0-46bf121bdc35.png)

**Comment by 0xApt** [comment]
Thanks for the feedback and screenshots! I've updated the script and removed the repositories :)
